# Generated by Django 6.0.2 on 2026-02-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='prn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
