# Generated by Django 5.2.11 on 2026-03-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_college_password_college_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='college',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
